config/routes.rb
Rails.application.routes.draw do

  resources :programs
  root 'programs#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :program
	has_many :event_users
	accepts_nested_attributes_for :event_users, allow_destroy: true

	def end_time
		Event.where("from > ?", Time.now)
	end
end

app/models/event_user.rb
class EventUser < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord
	has_many :events
	accepts_nested_attributes_for :events,allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def index
  	
  	@p = Program.search(params[:q])
  	@programs = @p.result
  end
  def show
  	@program = Program.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/layouts/_footer.html.erb
<footer class="container">
	<div class="col-md-10 col-md-offset-1" id="footer-line">
		<div class="pull-left">
			<ul>
				<li>Home</li>
				<li>About</li>
				<li>Contact</li>
			</ul>
		</div>
		<div class="pull-right">
			<ul>
				<li>Advertise</li>
				<li>Privacy</li>
				<li>Terms</li>
			</ul>
		</div>
	</div>
	
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">IvyProgram</a>
    </div>
    <ul class="nav navbar-nav  hidden-xs">
     <% if (current_page?(root_path) || current_page?(programs_path) ) %>
      <%= search_form_for @p, :url => programs_path, :html => {:method => :get, class: "navbar-form navbar-left"} do |f| %>
        <div class="form-group">
          <%= f.text_field :name_cont, class: "form-control", placeholder: "Search" %>
        </div>
      <% end %>
    <% else %>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="search" name="" class="form-control" placeholder="Search">
        </div>
      </form> 
    <% end %>
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span></a></li>
     
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ivyprograms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<%= render "layouts/nav" %>
  	<div class="container">
  		 <%= yield %>
  	</div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/programs/index.html.erb
<style type="text/css">
	tr{
		background-color: 
	}
</style>

<div class="program-index">
	<div class="col-md-10 col-md-offset-1">
		<div class="second-nav">
			<div>
				<p>All Programs &nbsp;<i class="fa fa-angle-down"></i> <a href="" class="pull-right">New +</a></p>

			</div>
		</div>
		<div class="third-nav">
			<div>
				<p>
					<a href="" class="pull-right" id="list_view"><i class="fa fa-bars" aria-hidden="true"></i></a>&emsp;&emsp;
					<a href="" class="pull-right" id="grid_view"><i class="fa fa-th" aria-hidden="true"></i></a>
				</p>

			</div>
		</div>

		<table class="table table-condensed">
		    <thead>
		      <tr>
		        <th>Name</th>
		        <th><%= sort_link(@p, :start_date, 'Start') %></th>
		        <th><%= sort_link(@p, :end_date, 'End') %></th>
		      </tr>
		    </thead>

		    <tbody>
		    	<% if @programs.exists? %>
			      	<% @programs.each do |p| %>
				        <% if DateTime.now.to_date > p.end_date %>
					        <tr style="background-color: #e2e2e5; ">
					      	    <td><%= p.name %> (Times's UP)</td>
						        <td><%= p.start_date.strftime('%e %b %Y') %></td>
						        <td><%= p.end_date.strftime('%e %b %Y') %></td>
						    </tr>
						<% else %>
							<tr>
					      	    <td><%= link_to p.name, p %></td>
						        <td><%= p.start_date.strftime('%e %b %Y') %></td>
						        <td><%= p.end_date.strftime('%e %b %Y') %></td>
						        <td></td>
						    </tr>
						<% end %>

				    <% end %>
		        <% else %>
			    	<td><h3 class="text-center">Looking for program not found</h3></td>
		        <% end %>
		      
		    </tbody>
		</table>

		<div class="grid" style="display: none;">
			<% if @programs.exists? %>
			    <% @programs.each do |p| %>
					<div class="col-md-3">
						<div class="thumbnail">
							<div class="caption">
								<p><%= p.name.truncate(15) %></p>
							</div>
						</div>
					</div>
				<% end %>
	        <% else %>
		    	<td><h3 class="text-center">Looking for program not found</h3></td>
	        <% end %>
			
		</div>
	</div>
	
</div>


 

app/views/programs/show.html.erb
<div class="programs-show">
	<div class="col-md-10 col-md-offset-1">
		<p id="border-show"><%= @program.name %> 
			<span class="pull-right">
				Start:<%= @program.start_date.strftime('%e %b %Y') %>&emsp; End: <%= @program.end_date.strftime('%e %b %Y') %>
				&emsp;&emsp; <a href="">New event</a>
			</span>
		</p>
		<div class="events">
			<% @program.events.each do |event| %>
				

				<div class="col-md-3">
					<div class="thumbnail">
						<p><%= event.to.strftime('%-H:00') %>
							<span class="pull-right"><%= event.from.strftime('%-H:00') %></span>
						</p>
						<p><%= event.name %></p>
						<% if event.event_users %>
							<% event.event_users.each do |user| %>
								<p><%= user.name %></p>
							<% end %>
						<% else %>
							<p>No users for this event</p>
						<% end %>
						
					</div>
				</div>
			<% end %>
		</div>
		
	</div>
</div>